services:
  db:
    image: postgres:15
    container_name: portifolio_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: adminlaura123
      POSTGRES_DB: portifolio_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data